set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y17} [get_ports ADC0_SYNC]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA16} [get_ports ADC0_PDWN]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB16} [get_ports ADC0_CSB]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB17} [get_ports ADC0_SDIO]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA13} [get_ports ADC0_SCLK]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB13} [get_ports ADC1_SYNC]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB15} [get_ports ADC1_PDWN]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y13} [get_ports ADC1_CSB]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AA14} [get_ports ADC1_SDIO]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN W14} [get_ports ADC1_SCLK]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN Y14} [get_ports BUFFER_CTRLA]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN AB11} [get_ports BUFFER_CTRLB]
# set_property -dict { IOSTANDARD LVCMOS18 PACKAGE_PIN W11   DIFF_TERM TRUE } [get_ports CLK_A7_C_REFB_P ]
# set_property -dict { IOSTANDARD LVCMOS18 PACKAGE_PIN W12   DIFF_TERM TRUE } [get_ports CLK_A7_C_REFB_N ]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C18 DIFF_TERM 1} [get_ports CLK_A7_C_REFA_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C19 DIFF_TERM 1} [get_ports CLK_A7_C_REFA_N]

# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C2 } [get_ports TEMP_SCL         ]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B2 } [get_ports TEMP_SDA         ]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D1 } [get_ports CFG_DAC0_SDO     ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E2} [get_ports CFG_DAC0_SDIO]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D2} [get_ports CFG_DAC0_SCLK]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P6} [get_ports CFG_DAC0_SDENB_N]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G1 } [get_ports ALARM_DAC0       ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F1} [get_ports TXENABLE_DAC0]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F3} [get_ports RESET_DAC0_N]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E3} [get_ports SLEEP_DAC0]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K1 } [get_ports CFG_DAC1_SDO     ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J1} [get_ports CFG_DAC1_SDIO]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H2} [get_ports CFG_DAC1_SCLK]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports CFG_DAC1_SDENB_N]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G2 } [get_ports ALARM_DAC1       ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K2} [get_ports TXENABLE_DAC1]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J2} [get_ports RESET_DAC1_N]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J5} [get_ports SLEEP_DAC1]
# set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN G21} [get_ports ZYT1_2V5         ]
# set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN G22} [get_ports ZYT2_2V5         ]
# set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN F21} [get_ports ZYT3_2V5         ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H5} [get_ports IO0_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H3} [get_ports IO1_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G3} [get_ports IO2_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN H4} [get_ports IO3_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G4} [get_ports IO4_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K4} [get_ports IO5_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J4} [get_ports IO6_DB_CB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L3} [get_ports IO7_DB_CB]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K3 } [get_ports KN_DB_CB         ]
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M1 } [get_ports KW_DB_CB         ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L1} [get_ports N4_SUM_CB_DB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M3} [get_ports N4_PK_CB_DB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M2} [get_ports W4_SUM_CB_DB]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K6} [get_ports W4_PK_CB_DB]
set_property -dict {IOSTANDARD LVCMOS25 PACKAGE_PIN M18} [get_ports F_TP1_2V5]
set_property -dict {IOSTANDARD LVCMOS25 PACKAGE_PIN N19} [get_ports F_TP2_2V5]
set_property -dict {IOSTANDARD LVCMOS25 PACKAGE_PIN K13} [get_ports F_TP3_2V5]
set_property -dict {IOSTANDARD LVCMOS25 PACKAGE_PIN L13} [get_ports F_TP4_2V5]
set_property -dict {IOSTANDARD LVCMOS25 PACKAGE_PIN E22} [get_ports FPGA_LED]

#############################################################################################################
### ARM Interface
#############################################################################################################
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J6} [get_ports SPI_ARM_A7_CLK]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L5} [get_ports SPI_ARM_A7_C0]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L4} [get_ports SPI_ARM_A7_MISO]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N4} [get_ports SPI_ARM_A7_MOSI]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N3} [get_ports GPIO0_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R1} [get_ports GPIO1_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P1} [get_ports GPIO2_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P5} [get_ports GPIO3_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P4} [get_ports GPIO4_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P2} [get_ports GPIO5_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N2} [get_ports GPIO6_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M6} [get_ports GPIO7_ARM_A7]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L6} [get_ports RST_ARM_FPGA_N]

#############################################################################################################
### TX DAC0
#############################################################################################################
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P15 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[0]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R16 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[0]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN N13 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[1]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN N14 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[1]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P16 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[2]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R17 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[2]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[3]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[3]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P19 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[4]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R19 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[4]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[5]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[5]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[6]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W22 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[6]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA20 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[7]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[7]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[8]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y22 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[8]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB21 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[9]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB22 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[9]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA19 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[10]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB20 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[10]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V17 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[11]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W17 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[11]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA18 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[12]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB18 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[12]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U17 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[13]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U18 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[13]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P14 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[14]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R14 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[14]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R18 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_P[15]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T18 DIFF_TERM 1} [get_ports {DATA_DAC0_DB_N[15]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U20 DIFF_TERM 1} [get_ports PARITY_DAC0_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V20 DIFF_TERM 1} [get_ports PARITY_DAC0_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W19 DIFF_TERM 1} [get_ports CLK_DATA_DAC0_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W20 DIFF_TERM 1} [get_ports CLK_DATA_DAC0_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y18 DIFF_TERM 1} [get_ports FRAME_DAC0_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y19 DIFF_TERM 1} [get_ports FRAME_DAC0_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V18 DIFF_TERM 1} [get_ports SYNC_DAC0_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V19 DIFF_TERM 1} [get_ports SYNC_DAC0_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN N17 DIFF_TERM 1} [get_ports OSTR_DAC0_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN P17 DIFF_TERM 1} [get_ports OSTR_DAC0_N]

#############################################################################################################
### TX DAC1
#############################################################################################################
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[0]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[0]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[1]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[1]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[2]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[2]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[3]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[3]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[4]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[4]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[5]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[5]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[6]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB1 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[6]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[7]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB2 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[7]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[8]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA3 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[8]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA5 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[9]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB5 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[9]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[10]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W5 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[10]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[11]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V5 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[11]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[12]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[12]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[13]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[13]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V7 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[14]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W7 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[14]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB7 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_P[15]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB6 DIFF_TERM 1} [get_ports {DATA_DAC1_DB_N[15]}]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN Y4 DIFF_TERM 1} [get_ports PARITY_DAC1_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA4 DIFF_TERM 1} [get_ports PARITY_DAC1_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V4 DIFF_TERM 1} [get_ports CLK_DATA_DAC1_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W4 DIFF_TERM 1} [get_ports CLK_DATA_DAC1_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN R4 DIFF_TERM 1} [get_ports FRAME_DAC1_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T4 DIFF_TERM 1} [get_ports FRAME_DAC1_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN T5 DIFF_TERM 1} [get_ports SYNC_DAC1_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN U5 DIFF_TERM 1} [get_ports SYNC_DAC1_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V9 DIFF_TERM 1} [get_ports OSTR_DAC1_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN V8 DIFF_TERM 1} [get_ports OSTR_DAC1_N]

#############################################################################################################
### RX ADC0
#############################################################################################################
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN B17 DIFF_TERM 1} [get_ports ADC0_FCO_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN B18 DIFF_TERM 1} [get_ports ADC0_FCO_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN D17 DIFF_TERM 1} [get_ports ADC0_DCO_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C17 DIFF_TERM 1} [get_ports ADC0_DCO_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN F13 DIFF_TERM 1} [get_ports ADC0_D0_A_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN F14 DIFF_TERM 1} [get_ports ADC0_D0_A_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C13 DIFF_TERM 1} [get_ports ADC0_D0_B_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN B13 DIFF_TERM 1} [get_ports ADC0_D0_B_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN D14 DIFF_TERM 1} [get_ports ADC0_D0_C_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN D15 DIFF_TERM 1} [get_ports ADC0_D0_C_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN E13 DIFF_TERM 1} [get_ports ADC0_D0_D_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN E14 DIFF_TERM 1} [get_ports ADC0_D0_D_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN F16 DIFF_TERM 1} [get_ports ADC0_D1_A_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN E17 DIFF_TERM 1} [get_ports ADC0_D1_A_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN B15 DIFF_TERM 1} [get_ports ADC0_D1_B_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN B16 DIFF_TERM 1} [get_ports ADC0_D1_B_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN E16 DIFF_TERM 1} [get_ports ADC0_D1_C_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN D16 DIFF_TERM 1} [get_ports ADC0_D1_C_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C14 DIFF_TERM 1} [get_ports ADC0_D1_D_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN C15 DIFF_TERM 1} [get_ports ADC0_D1_D_N]

#############################################################################################################
### RX ADC2
#############################################################################################################
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J20 DIFF_TERM 1} [get_ports ADC1_FCO_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J21 DIFF_TERM 1} [get_ports ADC1_FCO_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J19 DIFF_TERM 1} [get_ports ADC1_DCO_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H19 DIFF_TERM 1} [get_ports ADC1_DCO_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H13 DIFF_TERM 1} [get_ports ADC1_D0_A_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G13 DIFF_TERM 1} [get_ports ADC1_D0_A_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H20 DIFF_TERM 1} [get_ports ADC1_D0_B_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G20 DIFF_TERM 1} [get_ports ADC1_D0_B_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H17 DIFF_TERM 1} [get_ports ADC1_D0_C_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H18 DIFF_TERM 1} [get_ports ADC1_D0_C_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G17 DIFF_TERM 1} [get_ports ADC1_D0_D_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G18 DIFF_TERM 1} [get_ports ADC1_D0_D_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G15 DIFF_TERM 1} [get_ports ADC1_D1_A_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN G16 DIFF_TERM 1} [get_ports ADC1_D1_A_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J22 DIFF_TERM 1} [get_ports ADC1_D1_B_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H22 DIFF_TERM 1} [get_ports ADC1_D1_B_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J15 DIFF_TERM 1} [get_ports ADC1_D1_C_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H15 DIFF_TERM 1} [get_ports ADC1_D1_C_N]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN J14 DIFF_TERM 1} [get_ports ADC1_D1_D_P]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN H14 DIFF_TERM 1} [get_ports ADC1_D1_D_N]

set_property LOC IDELAYCTRL_X0Y4 [get_cells u_adc0_intf/ADC_interface_inst/AD_CLK_GENERATE_inst/IDELAYCTRL_inst]
set_property LOC IDELAYCTRL_X0Y3 [get_cells u_adc1_intf/ADC_interface_inst/AD_CLK_GENERATE_inst/IDELAYCTRL_inst]











